#@author    Salman Omar Sohail <support@mybotshop.de>
#@copyright (c) 2025, MYBOTSHOP GmbH, Inc., All rights reserved.

/**:
  ros__parameters:
    robot_map_topic: "map"
    robot_cmd_vel: "webserver/cmd_vel"
    robot_e_stop: "e_stop"
    robot_gps_lat: 50.9533
    robot_gps_lon: 6.60266
    robot_password: "123"
    robot_gps_topic: "fixposition/navsatfix"
    robot_battery_topic: "sensor/battery/state"
    robot_webserver: "g1-webserver"
    robot_max_linear_velocity: 0.1
    robot_max_angular_velocity: 0.1
    robot_home_dir: "/home/unitree"
    robot_rosbag_dir: "/opt/mybotshop/bags/"
    robot_rosbag_storage: 1000000000
    robot_rosbag_duration: 1800
    robot_services:
      [
      # "g1-llm",
      # "g1-arm-7dof",
      "g1-odometry",
      "g1-webserver",
      "g1-twist-mux",
      "g1-pcd-to-scan",
      "g1-led-service",
      "g1-description",
      "g1-video-stream",
      "g1-livox-mid360",
      "g1-audio-service",
      "g1-domain-bridge",
      "g1-state-publisher",
      # "g1-obstacle-avoidance",
      "g1-highlevel-ros-controller",
      ]
    web_security: true
    web_user: "admin"
    web_password: "mybotshop"
    web_server_ip: "0.0.0.0"
    web_server_port: 9000
