name: g1_unit_5849_domain_bridge
from_domain: 0
to_domain: 10
topics:
  /lf/lowstate:
    type: unitree_hg/msg/LowState
    remap: /lf/lowstate
  /lf/bmsstate:
    type: unitree_hg/msg/BmsState
    remap: /lf/bmsstate
  /lf/odommodestate:
    type: unitree_go/msg/SportModeState
    remap: /lf/odommodestate
