/**:
  ros__parameters:
    # g1_leghardware:
    eth: "eth0"

    # g1_statepublisher:
    robot_odom_pub: "odom_inverse_kinematics"
    robot_odom_tf: "odom"
    robot_baselink_tf: "base_link"

    # --- g1_video_publisher ---
    group: "230.1.1.1"
    port: 1720
    iface: "eth0"
    decoder: "avdec_h264"
    image_topic: "d435/image_raw"
    frame_id: "d435_link"
    latency_ms: 10
    qos_depth: 1
    drop_old: true
    sync: false
    publish_compressed: true
